program = "deno"
args = ["serve", "--allow-all", "main.ts"]
max-memory = 3_200
hugepage-arena-size = 64
hugepage-requests-arena = 8
# This remapping doesn't work.
# remapping = [ "0x1000000000:64:rw", "0xC00100000:128:rw" ]
env = ["DENO_V8_FLAGS=--single-threaded,--stress-maglev,--prepare-always-turbofan,--always-turbofan,--always-sparkplug,--max-old-space-size=256,--max-semi-space-size=256", "DENO_DIR=.cache/deno", "DENO_NO_UPDATE_CHECK=1"]
allow-connect = [ "127.0.0.53:53", "127.0.0.1:6379",  "0.0.0.0:8000", "jsr.io" ]
allow-listen = [ "0.0.0.0:8000" ]
allow-read = ["/dev/urandom", "/etc/resolv.conf", "/lib/x86_64-linux-gnu", "."]
allow-write = [".cache"]

