[package]
name = "kvmserver-examples-rust"
version = "0.1.0"
readme = "README.md"
edition = "2024"
publish = false

[dependencies]
httparse = "1.10.1"
tokio = { version = "1.44.2", features = ["full"] }

[build-dependencies]
cc = "1.0"
