#cloud-config
password: ubuntu
chpasswd: { expire: False }
ssh_pwauth: True
apt:
  sources:
    docker.list:
      source: deb [arch=amd64] https://download.docker.com/linux/ubuntu $RELEASE stable
      keyid: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
packages:
  - docker-ce
  - docker-ce-cli
runcmd:
  - "usermod -a -G kvm -G docker ubuntu"
cloud_final_modules:
  - [scripts-user, always]
power_state:
  delay: now
  mode: poweroff
  message: Powering off after Cloud-init completion
  timeout: 2
  condition: true
